model:
  encoder:
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  decoder:
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  wavenet:
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  output-file: out.pth
dataset:
  definition-file: costam.csv
  audio-directory: ./dupa/

