model:                              # Konfiguracja parameterów uczenia
  encoder:                          # konfiguracja dla encodera
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  decoder:                          # konfiguracja dla decodera
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  wavenet:                          # konfiguracja dla wavenetu
    epochs: 20
    batch-size: 10
    learning-rate: 0.01
  output-file: out.pth
dataset:                            # Konfiguracja zestawu danych uczących
  root-dir: .
  definition-file: costam.csv       # csv z opisem i powiązaniem wypowiedzi tekstowych z plikami csv
  audio-directory: /audio         # ścieżka do plików audio w kontekscie root-dir np. root-dir/sciezka


